### PR TITLE
Support other Atproto services

### PR DESCRIPTION
**Pull request by yafesdot**
A little update to support other self or org-hosted PDS servers using Atproto

### CODE REVIEW

**Comment by yafesdot** [comment]
@yafes.bsky.social
Kudos would be appreciated :D

**Comment by handlerug** [comment]
Thank you for your contribution! Do you have an example profile hosted elsewhere (i.e. not on bsky.social) I can try?

The "Advanced Settings" button doesn't look very nice. What do you think about adding it as a "show advanced settings" link after the "source code" link? Not distracting yet easily reachable.

There are some fluke whitespace changes in this PR. You can fix that by running Prettier on changed files to normalize formatting.

**Comment by yafesdot** [comment]
> Thank you for your contribution! Do you have an example profile hosted elsewhere (i.e. not on bsky.social) **I can try**?

Well, if there is one I don't know either... I tested it on my local hosted atproto PDS.

image

> The "Advanced Settings" button doesn't look very nice. What do you think about adding it as a "show advanced settings" link after the "source code" link? Not distracting yet easily reachable.

As you can get from the general aesthetics of my additions on frontend I am not the best frontend designer yet to come :smiling_face_with_tear:. However I'll try to make it more "good-looking"! 

 > There are some fluke whitespace changes in this PR. You can fix that by running Prettier on changed files to normalize formatting.

Yeah sorry, I completely forgot to stylize.

**Comment by yafesdot** [comment]
Should be good to go, but check first ofc! @handlerug

**Comment by handlerug** [comment]
Thanks!

I can't navigate to the button with a keyboard. I meant that it should've been a `<button>`, but styled to appear like a link and placed into this bar:
The credits bar in the app

**Comment by handlerug** [comment]
And, like, make it say "show advanced settings" or "hide advanced settings" depending on the current state

**Comment by handlerug** [comment]
> Actually, it should be that way.

Oh yeah, sorry, just noticed that.

**Comment by yafesdot** [comment]
image
Is it looking good that way?

**Comment by yafesdot** [comment]
@handlerug

**Comment by handlerug** [comment]
Thanks!

**Pull request merged**
